project:
  type: website
  output-dir: _site

website:
  title: "Natalie Truesdell"
  site-url: https://natalie1339.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: experience.qmd
        text: Experience
    right:
      - icon: github
        href: https://github.com/Natalie1339
      - icon: linkedin
        href: https://www.linkedin.com/in/natalie-truesdell-948499285/

format:
  html:
    theme: [sandstone, custom.scss]
    toc: false



