project:
  type: website
  output-dir: _site

website:
  title: "Natalie Truesdell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: experience.qmd
        text: Experience
    right:
      - icon: github
        href: https://github.com/Natalie1339
      - icon: linkedin
        href: https://www.linkedin.com/in/natalie-truesdell-948499285/

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false



